### ISSUE TITLE
Locker

### ISSUE THREAD

**Issue by xDope7137** [TheBritishBrotherhood/TPRP-BASE-PUBLIC#1]
Hello, thanks a lot for sharing this server files. I loved it a lot. The only thing that was created with "lockers" in disc-inventory.

There is no SQL for this part of the script. I would love it I get that. Thanks again!

**Comment by Fr1endo420** [comment]
Same problem 😔

**Comment by AlucardVoss** [comment]
It isent that hard tho

`CREATE TABLE `lockers` (
  `identifier` varchar(50) DEFAULT NULL,
  `paid` varchar(255) DEFAULT NULL,
  `lastpayment` int(255) DEFAULT NULL,
  `lockername` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;`

**Comment by xDope7137** [comment]
@AlucardVoss Also there is "lockers_auth" table.

Thanks for this also :)

**Comment by AlucardVoss** [comment]
Meh works for me 

CREATE TABLE `lockers_auth` (
  `code` varchar(255) DEFAULT NULL,
  `generated` time DEFAULT NULL,
  `used` int(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
