### ISSUE TITLE
Is it me or theres no housing ?

### ISSUE THREAD

**Issue by AlucardVoss** [TheBritishBrotherhood/TPRP-BASE-PUBLIC#2]
Resource tp-housing is broken ?

**Comment by xDope7137** [comment]
DM me on xDope#2788 I will send you fixed one

**Comment by AlucardVoss** [comment]
Added you as JaceSkell

**Comment by suraj1996a** [comment]
Either cant find motels or furni script

**Comment by TheBritishBrotherhood** [comment]
Motels, Funri were removed.

**Comment by suraj1996a** [comment]
@TheBritishBrotherhood would add gcphone and motel to.

**Comment by suraj1996a** [comment]
it is easier to work on it. and thanks for this amazing server
